/* Generates serpent-battery-standalone.html — a single portable file with the
   engine, the shared modules, and the shared stylesheet all inlined.

   This exists because the standalone is what render-test.mjs boots. Hand-syncing
   it (which is what happened before this script existed) means the render test
   silently checks stale code the moment the sources move.

   Run:  node games/serpent-battery/build.mjs
*/
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const shared = join(here, '..', '..', 'shared');

const read = (p) => readFileSync(p, 'utf8');

/** Every top-level declaration in a module, exported or not. The inlined IIFE
 *  returns all of them, because the shell reaches for a few internals that
 *  aren't formally exported. */
function topLevelNames(src) {
  const names = [];
  const re = /^(?:export\s+)?(?:const|let|var|function)\s+([A-Za-z_$][\w$]*)/gm;
  let m;
  while ((m = re.exec(src))) if (!names.includes(m[1])) names.push(m[1]);
  return names;
}

/** Turn an ES module into an IIFE that evaluates to its exports object. */
function inlineModule(src) {
  const names = topLevelNames(src);
  const body = src
    .replace(/^export\s+/gm, '')                       // drop export keywords
    .replace(/^import[^;]*;\s*$/gm, '');               // drop any imports
  return `(() => {\n${body}\nreturn { ${names.join(', ')} };\n})()`;
}

const BANNER = '/* Generated by build.mjs — do not edit. Edit engine.js and serpent-battery.html. */';

/** Replace `url('./fonts/x.woff2')` with a base64 data URI, so the inlined
 *  stylesheet carries its own fonts. Throws rather than silently shipping a
 *  build whose text renders in a fallback face. */
function embedFonts(css) {
  return css.replace(/url\(['"]?\.\/fonts\/([\w.-]+\.woff2)['"]?\)/g, (_, file) => {
    const bytes = readFileSync(join(shared, 'fonts', file));
    return `url(data:font/woff2;base64,${bytes.toString('base64')})`;
  });
}

function build() {
  let html = read(join(here, 'serpent-battery.html'));

  // 1. inline the shared stylesheet where the <link> was, with its fonts
  //    embedded as data URIs — the CSS lands in a <style> in this directory,
  //    so its './fonts/...' paths would otherwise resolve to nothing, and the
  //    point of the standalone is that it works as a single file.
  const theme = embedFonts(read(join(shared, 'theme.css')));
  html = html.replace(
    /<link rel="stylesheet" href="\.\.\/\.\.\/shared\/theme\.css">/,
    `<style>\n/* --- inlined from shared/theme.css --- */\n${theme}</style>`
  );

  // 2. replace the module imports with inlined IIFEs
  const engine = inlineModule(read(join(here, 'engine.js')));
  const fit = inlineModule(read(join(shared, 'fit.js')));

  html = html.replace(
    /^import \* as E from '\.\/engine\.js';$/m,
    `${BANNER}\nconst E = ${engine};`
  );
  html = html.replace(
    /^import \{ makeFit \} from '\.\.\/\.\.\/shared\/fit\.js';$/m,
    `const { makeFit } = ${fit};`
  );

  // JS imports only — CSS's own `@import url(...)` is legitimate and stays.
  const stray = html.match(/^\s*import\s.+$/m);
  if (stray) {
    throw new Error(`an import survived inlining, the standalone would not load: ${stray[0].trim()}`);
  }

  writeFileSync(join(here, 'serpent-battery-standalone.html'), html);
  console.log('wrote serpent-battery-standalone.html');
}

build();
