/* Turn a game's HTML shell into a single self-contained document — no imports,
   no stylesheet link, no external references of any kind.

   Two callers want this, for different reasons:

   - `games/flak-battery/build.mjs`, which writes the result to disk as the
     distributable single-file build.
   - the render tests, which boot the result in jsdom to catch draw-path crashes
     that pure-logic tests cannot see. They inline in memory rather than needing
     a checked-in artifact, which is why the other three games can have render
     tests without also gaining a standalone build to keep in sync.

   It replaced a version specific to one game (then Serpent Battery, now Flak Battery) that listed each import by
   hand and stripped imports it did not recognise. That silently broke when
   `shared/help.js` gained an import of its own (`version.js`): the nested
   import was deleted, `BUILD_LABEL` became a free variable, and the shell threw
   at boot. Modules are now resolved *recursively*, so a shared module gaining a
   dependency is no longer a trap. */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/** Every top-level declaration in a module, exported or not. The inlined IIFE
 *  returns all of them, because shells reach for a few internals that aren't
 *  formally exported. */
function topLevelNames(src) {
  const names = [];
  const re = /^(?:export\s+)?(?:const|let|var|function)\s+([A-Za-z_$][\w$]*)/gm;
  let m;
  while ((m = re.exec(src))) if (!names.includes(m[1])) names.push(m[1]);
  return names;
}

const IMPORT_RE = /^import\s+(.+?)\s+from\s+['"]([^'"]+)['"];?\s*$/gm;

/** Parse the import statements of a module into {clause, spec} pairs. */
function parseImports(src) {
  const out = [];
  for (const m of src.matchAll(IMPORT_RE)) out.push({ raw: m[0], clause: m[1].trim(), spec: m[2] });
  return out;
}

/** The binding an import clause introduces, given the name of the variable
 *  holding the resolved module object. */
function bindingFor(clause, modVar) {
  const ns = clause.match(/^\*\s+as\s+([A-Za-z_$][\w$]*)$/);
  if (ns) return `const ${ns[1]} = ${modVar};`;
  /* A named clause becomes a destructuring pattern — but `import {a as b}` and
     `const {a: b}` spell renaming differently, so the aliases have to be
     translated. Passing `{ set as setPref }` straight through emitted
     `const { set as setPref } = …`, which is a SyntaxError that took the whole
     shell down; the render test caught it, which is the only reason this is a
     one-line bug and not a shipped one. */
  if (clause.startsWith('{')) {
    const renamed = clause.replace(/([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)/g, '$1: $2');
    return `const ${renamed} = ${modVar};`;
  }
  // No module in this repo has a default export; fail loudly rather than
  // emitting something that silently resolves to undefined.
  throw new Error(`unsupported import clause "${clause}" — only namespace and named imports are handled`);
}

/**
 * Inline a module and everything it imports, depth first.
 * @param file      absolute path to the module
 * @param emitted   Map of path -> variable name, shared across the whole graph
 * @param chunks    array collecting `const __mod_N = (() => {...})();` strings
 * @returns the variable name holding this module's exports
 */
function inlineModule(file, emitted, chunks) {
  const already = emitted.get(file);
  if (already) return already;

  const src = readFileSync(file, 'utf8');
  const modVar = `__mod_${emitted.size}`;
  // Reserve the name before recursing, so an import cycle terminates rather
  // than recursing forever. (Nothing here is cyclic today; this is a guard.)
  emitted.set(file, modVar);

  let body = src;
  for (const imp of parseImports(src)) {
    const dep = resolve(dirname(file), imp.spec);
    const depVar = inlineModule(dep, emitted, chunks);
    body = body.replace(imp.raw, bindingFor(imp.clause, depVar) + '\n');
  }
  body = body.replace(/^export\s+/gm, '');

  chunks.push(`const ${modVar} = (() => {\n${body}\nreturn { ${topLevelNames(src).join(', ')} };\n})();`);
  return modVar;
}

/** Replace `url('./fonts/x.woff2')` with a base64 data URI, so the inlined
 *  stylesheet carries its own fonts. The CSS ends up in a <style> in a
 *  different directory, so './fonts/...' would otherwise resolve to nothing —
 *  and the text would quietly render in a fallback face. */
function embedFonts(css, sharedDir) {
  return css.replace(/url\(['"]?\.\/fonts\/([\w.-]+\.woff2)['"]?\)/g, (_, file) => {
    const bytes = readFileSync(resolve(sharedDir, 'fonts', file));
    return `url(data:font/woff2;base64,${bytes.toString('base64')})`;
  });
}

const BANNER = '/* Generated by tools/inline.mjs — do not edit. Edit the game\'s engine.js and .html. */';

/**
 * @param htmlPath  absolute path to a game shell (e.g. .../hull-breach.html)
 * @returns the self-contained HTML as a string
 */
export function inlineGame(htmlPath) {
  const here = dirname(htmlPath);
  let html = readFileSync(htmlPath, 'utf8');

  // 1. the shared stylesheet, with its fonts embedded
  const linkMatch = html.match(/<link rel="stylesheet" href="([^"]+)">/);
  if (linkMatch) {
    const cssPath = resolve(here, linkMatch[1]);
    const css = embedFonts(readFileSync(cssPath, 'utf8'), dirname(cssPath));
    html = html.replace(linkMatch[0], `<style>\n/* --- inlined from ${linkMatch[1]} --- */\n${css}</style>`);
  }

  // 2. drop everything pointing outside this file. A standalone travels alone,
  //    so the cabinet link, manifest, icons and service-worker registration all
  //    resolve to nothing — and a failed registration logs on every load.
  html = html.replace(/\s*<a class="back"[^>]*>.*?<\/a>/s, '');
  html = html.replace(/\s*<link rel="manifest"[^>]*>/, '');
  html = html.replace(/\s*<link rel="icon"[^>]*>/, '');
  html = html.replace(/\s*<link rel="apple-touch-icon"[^>]*>/, '');
  html = html.replace(/\s*<script type="module" src="[^"]*pwa\.js"><\/script>/, '');

  // 3. the inline module script: resolve its whole import graph
  const scriptRe = /<script type="module">([\s\S]*?)<\/script>/;
  const script = html.match(scriptRe);
  if (!script) throw new Error(`${htmlPath} has no inline <script type="module">`);

  const emitted = new Map();
  const chunks = [];
  let body = script[1];
  for (const imp of parseImports(body)) {
    const depVar = inlineModule(resolve(here, imp.spec), emitted, chunks);
    body = body.replace(imp.raw, bindingFor(imp.clause, depVar) + '\n');
  }

  html = html.replace(scriptRe, () =>
    `<script type="module">\n${BANNER}\n${chunks.join('\n')}\n${body}\n</script>`);

  // JS imports only — CSS's own `@import url(...)` is legitimate and stays.
  const stray = html.match(/^\s*import\s.+$/m);
  if (stray) {
    throw new Error(`an import survived inlining, the file would not load: ${stray[0].trim()}`);
  }
  return html;
}
